#!/usr/bin/perl
$target = shift(@ARGV);
$home = $ENV{'HOME'};
$mydata = "$home/mydata";
#print "target=".$target."\n";
if ($target eq "oj" || $target eq "openjdk"){
	$dir="$mydata/csprojects/openjdk";
}
elsif ($target eq "jdk6064" || $target eq "6064"){
	$dir="$mydata/csprojects/jdk6064default";
}
elsif($target eq "jdk6064cr" || $target eq "6064cr"){
	$dir = "$mydata/csprojects/jdk6064compressedrefs";
}
elsif ($target eq "jdk7064" || $target eq "7064"){
	$dir="$mydata/csprojects/jdk7064default";
}
elsif ($target eq "jdk7064cr" || $target eq "7064cr"){
	$dir="$mydata/csprojects/jdk7064compressedrefs";
}
elsif ($target eq "jdk7164" || $target eq "7164"){
	$dir="$mydata/csprojects/jdk7164default";
}
elsif ($target eq "jdk7164cr" || $target eq "7164cr"){
	$dir="$mydata/csprojects/jdk7164compressedrefs";
}
elsif ($target eq "jdk7032" || $target eq "7032"){
	$dir="$mydata/csprojects/jdk7032";
}
elsif ($target eq "jdk7132" || $target eq "7132"){
	$dir="$mydata/csprojects/jdk7132";
}
elsif ($target eq "jdk8064" || $target eq "8064"){
	$dir="$mydata/csprojects/jdk8064default";
}
elsif ($target eq "jdk8064cr" || $target eq "8064cr"){
	$dir="$mydata/csprojects/jdk8064compressedrefs";
}
elsif ($target eq "jdk8032" || $target eq "8032"){
	$dir="$mydata/csprojects/jdk8032";
}
elsif ($target eq "jdk62632" || $target eq "62632"){
	$dir="$mydata/csprojects/jdk62632";
}
elsif ($target eq "jdk62664" || $target eq "62664"){
	$dir="$mydata/csprojects/jdk62664";
}
elsif ($target eq "jdk62664cr" || $target eq "62664cr"){
	$dir="$mydata/csprojects/jdk62664compressedrefs";
}

elsif($target eq "jdk5032" || $target eq "5032"){
	$dir = "$mydata/csprojects/jdk5032";
}
elsif($target eq "jdk5064" || $target eq "5064"){
	$dir = "$mydata/csprojects/jdk5064";
}
elsif($target eq "jdk1464" || $target eq "1464"){
	$dir = "$mydata/csprojects/jdk1464";
}
elsif($target eq "jdk6032" || $target eq "6032"){
	$dir = "$mydata/csprojects/jdk6032";
}
elsif($target eq "v6r1" || $target eq "61"){
	$dir = "$mydata/csprojects/61";
}
elsif($target eq "v5r4" || $target eq "54"){
	$dir = "$mydata/csprojects/54";
}
elsif($target eq "v7r1" || $target eq "71"){
	$dir = "$mydata/csprojects/71";
}
elsif($target eq "v7r2" || $target eq "72"){
	$dir = "$mydata/csprojects/72";
}
elsif($target eq "v6r1m13" || $target eq "6113"){
	$dir = "$mydata/csprojects/6113";
}
elsif($target eq "v6r1m14" || $target eq "6114"){
	$dir = "$mydata/csprojects/6114";
}
elsif($target eq "v6r1m15" || $target eq "6115"){
	$dir = "$mydata/csprojects/6115";
}
elsif($target eq "v6r1m16" || $target eq "6116"){
	$dir = "$mydata/csprojects/6116";
}
elsif($target eq "v6r1m17" || $target eq "6117"){
	$dir = "$mydata/csprojects/6117";
}
elsif($target eq "v5r4m11" || $target eq "5411"){
	$dir = "$mydata/csprojects/5411";
}
elsif($target eq "kvm"){
	$dir = "$mydata/csprojects/kvm";
}
elsif($target eq "linux"){
	$dir = "$mydata/csprojects/linuxKernal";
}
elsif($target eq "jcl"){
	$dir = "$mydata/csprojects/jcl";
}
else{
	$dir =".";
}
print "$dir";
